# Konfigurasi Global (Gunakan jika semua perangkat punya kredensial yang sama)
credentials:
  username: "admin"
  password: "SuperPassword123"
  secret: "EnablePassword123"

# Daftar Perangkat Jaringan Anda
devices:
  - name: "Router-Core-Jakarta"
    host: "192.168.1.254"
    device_type: "cisco_ios"   # Digunakan oleh Netmiko
    driver: "ios"              # Digunakan oleh NAPALM

  - name: "Switch-Layer2-Sby"
    host: "10.0.0.5"
    device_type: "cisco_ios"
    driver: "ios"

  - name: "Juniper-Edge"
    host: "172.16.10.1"
    device_type: "juniper_junos"
    driver: "junos"

  - name: "Mikrotik-Main-Router"
    host: "192.168.88.1"
    device_type: "mikrotik_routeros" # Driver untuk Netmiko
